export type AnimationLabCategory =
  | "Hover"
  | "Scroll"
  | "Typography"
  | "Glass"
  | "Blueprint"
  | "Map"
  | "Card"
  | "Advanced";

export type AnimationLabDifficultyLabel =
  | "Kolay"
  | "Orta"
  | "Zor"
  | "Çok Zor";

export type AnimationLabItem = {
  id: string;
  title: string;
  category: AnimationLabCategory;
  difficulty: 1 | 2 | 3 | 4 | 5;
  difficultyLabel: AnimationLabDifficultyLabel;
  description: string;
  instruction: string;
};

export const categoryFilters = [
  "Tümü",
  "Hover",
  "Scroll",
  "Typography",
  "Glass",
  "Blueprint",
  "Map",
  "Card",
  "Advanced",
] as const;

export const difficultyFilters = [
  "Tümü",
  "Kolay",
  "Orta",
  "Zor",
  "Çok Zor",
] as const;

export type CategoryFilter = (typeof categoryFilters)[number];
export type DifficultyFilter = (typeof difficultyFilters)[number];

export const animationLabItems: AnimationLabItem[] = [
  {
    id: "cursor-light-inspector",
    title: "Cursor Light Inspector",
    category: "Hover",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Mouse hareketini takip eden kontrollü radial ışık alanı.",
    instruction: "Mouse hareketi",
  },
  {
    id: "glass-refraction-cursor",
    title: "Glass Refraction Cursor",
    category: "Glass",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Cam yüzeyde mouse yönüne göre kayan diagonal yansıma.",
    instruction: "Mouse hareketi",
  },
  {
    id: "dynamic-corner-brackets",
    title: "Dynamic Corner Brackets",
    category: "Card",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Hover ile açılan teknik çizim köşe işaretleri.",
    instruction: "Hover",
  },
  {
    id: "card-border-wake",
    title: "Card Border Wake",
    category: "Card",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Köşeden başlayıp kart çevresini dolaşan ince border izi.",
    instruction: "Hover",
  },
  {
    id: "soft-shadow-depth-shift",
    title: "Soft Shadow Depth Shift",
    category: "Hover",
    difficulty: 1,
    difficultyLabel: "Kolay",
    description: "Ölçek değiştirmeden derinlik ve gölge hissi üretir.",
    instruction: "Hover",
  },
  {
    id: "magnetic-cta",
    title: "Magnetic CTA",
    category: "Hover",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Buton, imlece doğru ölçülü ve premium bir çekim uygular.",
    instruction: "Mouse hareketi",
  },
  {
    id: "cta-arrow-glide",
    title: "CTA Arrow Glide",
    category: "Hover",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "CTA oku hover sırasında geri çekilip ileri kayar.",
    instruction: "Hover",
  },
  {
    id: "architectural-noise-breathing",
    title: "Architectural Noise Breathing",
    category: "Glass",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Noise ve yüzey gradienti neredeyse fark edilmez biçimde nefes alır.",
    instruction: "Hover",
  },
  {
    id: "micro-blueprint-coordinates",
    title: "Micro Blueprint Coordinates",
    category: "Blueprint",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Akışkan grid ve mikro koordinat notları ile teknik doku verir.",
    instruction: "Hover",
  },
  {
    id: "blueprint-grid-compression",
    title: "Blueprint Grid Compression",
    category: "Blueprint",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Grid çizgileri hover sırasında sıkışarak mimari düzene oturur.",
    instruction: "Hover",
  },
  {
    id: "blueprint-line-draw",
    title: "Blueprint Line Draw",
    category: "Blueprint",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "SVG stroke çizimleri teknik plan gibi sırayla belirir.",
    instruction: "Hover",
  },
  {
    id: "dynamic-blueprint-lens",
    title: "Dynamic Blueprint Lens",
    category: "Blueprint",
    difficulty: 5,
    difficultyLabel: "Çok Zor",
    description: "Mouse çevresinde blueprint katmanını açan lokal lens etkisi.",
    instruction: "Mouse hareketi",
  },
  {
    id: "manifesto-line-activation",
    title: "Manifesto Line Activation",
    category: "Typography",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Üç satırlık manifesto metni hover ile sırayla parlaklaşır.",
    instruction: "Hover",
  },
  {
    id: "mask-based-title-reveal",
    title: "Mask-Based Title Reveal",
    category: "Typography",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Başlık, mask içinde yukarıdan açılıyormuş gibi görünür.",
    instruction: "Hover",
  },
  {
    id: "text-reflection-sweep",
    title: "Text Reflection Sweep",
    category: "Typography",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Büyük başlık üzerinden ince bir yansıma çizgisi geçer.",
    instruction: "Hover",
  },
  {
    id: "red-keyword-activation",
    title: "Red Keyword Activation",
    category: "Typography",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Cümledeki vurgu kelimesi hover ile kırmızı aksana geçer.",
    instruction: "Hover",
  },
  {
    id: "founder-signature-draw",
    title: "Founder Signature Draw",
    category: "Typography",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Kurucu imzasını andıran SVG çizgi stroke ile yazılır.",
    instruction: "Hover",
  },
  {
    id: "project-image-depth-reveal",
    title: "Project Image Depth Reveal",
    category: "Card",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Katmanlar farklı hızlarda kayarak yalancı derinlik oluşturur.",
    instruction: "Mouse hareketi",
  },
  {
    id: "project-card-portal-hover",
    title: "Project Card Portal Hover",
    category: "Card",
    difficulty: 5,
    difficultyLabel: "Çok Zor",
    description: "Hover ile kart merkezinde kontrollü bir pencere hissi açılır.",
    instruction: "Hover",
  },
  {
    id: "material-layer-peel",
    title: "Material Layer Peel",
    category: "Advanced",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Üst yüzey hafif soyulur, alttaki teknik çizgiler görünür.",
    instruction: "Hover",
  },
  {
    id: "glass-panel-depth-stack",
    title: "Glass Panel Depth Stack",
    category: "Glass",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Üst üste duran cam paneller hover ile katmanlara ayrılır.",
    instruction: "Hover",
  },
  {
    id: "liquid-border-distortion",
    title: "Liquid Border Distortion",
    category: "Glass",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Border çizgisi abartısız, canlı ve akışkan bir titreşim taşır.",
    instruction: "Hover",
  },
  {
    id: "specular-highlight-sweep",
    title: "Specular Highlight Sweep",
    category: "Glass",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Cam yüzeyden kontrollü diagonal ışık çizgisi geçer.",
    instruction: "Hover",
  },
  {
    id: "footer-reveal-curtain",
    title: "Footer Reveal Curtain",
    category: "Scroll",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Mini footer alanı perde gibi yukarı açılıp içeriği gösterir.",
    instruction: "Tıkla",
  },
  {
    id: "section-magnetic-title",
    title: "Section Magnetic Title",
    category: "Scroll",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Başlık hover ile hafifçe yukarı tutunur, sonra yerine döner.",
    instruction: "Hover",
  },
  {
    id: "scroll-velocity-grain",
    title: "Scroll Velocity Grain",
    category: "Scroll",
    difficulty: 5,
    difficultyLabel: "Çok Zor",
    description: "Kart içi scroll hızlandıkça grain/noise yoğunluğu artar.",
    instruction: "Kart içinde scroll",
  },
  {
    id: "adaptive-page-tint",
    title: "Adaptive Page Tint",
    category: "Scroll",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Mini section seçimleri arka plan tonunu kontrollü değiştirir.",
    instruction: "Tıkla",
  },
  {
    id: "map-pin-ripple",
    title: "Map Pin Ripple",
    category: "Map",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Harita pini çevresinden sakin ripple halkaları yayılır.",
    instruction: "Hover",
  },
  {
    id: "road-network-draw",
    title: "Road Network Draw",
    category: "Map",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "SVG yol ağları stroke animasyonuyla plan üstünde çizilir.",
    instruction: "Hover",
  },
  {
    id: "location-radar-sweep",
    title: "Location Radar Sweep",
    category: "Map",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Pin çevresinde dönen radar çizgisi lokasyon odağı verir.",
    instruction: "Hover",
  },
  {
    id: "distance-counter-lines",
    title: "Distance Counter Lines",
    category: "Map",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "İki nokta arasında akan çizgi ve hareketli süre etiketi.",
    instruction: "Hover",
  },
  {
    id: "input-focus-breathing",
    title: "Input Focus Breathing",
    category: "Hover",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Mini input focus alınca kırmızı glow nefes alır.",
    instruction: "Tıkla",
  },
  {
    id: "submit-success-morph",
    title: "Submit Success Morph",
    category: "Hover",
    difficulty: 3,
    difficultyLabel: "Orta",
    description: "Buton tıklandığında gönderimden check ikonlu başarı durumuna geçer.",
    instruction: "Tıkla",
  },
  {
    id: "tiny-data-flicker",
    title: "Tiny Data Flicker",
    category: "Advanced",
    difficulty: 2,
    difficultyLabel: "Kolay",
    description: "Teknik data satırları çok hafif flicker ile canlılık kazanır.",
    instruction: "Hover",
  },
  {
    id: "page-transition-origin-from-click-point",
    title: "Page Transition Origin From Click Point",
    category: "Advanced",
    difficulty: 5,
    difficultyLabel: "Çok Zor",
    description: "Tıklanan noktadan büyüyen daire kartı mini transition gibi kaplar.",
    instruction: "Tıkla",
  },
  {
    id: "text-to-plan-morph",
    title: "Text-to-Plan Morph",
    category: "Advanced",
    difficulty: 5,
    difficultyLabel: "Çok Zor",
    description: "Kısa kelime, çizgi ve grid formuna dönüşen mask demo üretir.",
    instruction: "Tıkla",
  },
  {
    id: "3d-building-volume-without-webgl",
    title: "3D Building Volume Without WebGL",
    category: "Advanced",
    difficulty: 5,
    difficultyLabel: "Çok Zor",
    description: "CSS ve SVG katmanlarıyla WebGL kullanmadan bina hacmi verir.",
    instruction: "Hover",
  },
  {
    id: "animated-construction-timeline",
    title: "Animated Construction Timeline",
    category: "Advanced",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Temel, kolon, cephe ve yaşam adımları sırayla aktive olur.",
    instruction: "Hover",
  },
  {
    id: "route-transition-with-depth-blur",
    title: "Route Transition With Depth Blur",
    category: "Advanced",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Eski mini panel blur alırken yeni panel derinlikle öne gelir.",
    instruction: "Tıkla",
  },
  {
    id: "premium-loading-less-preloader",
    title: "Premium Loading-less Preloader",
    category: "Advanced",
    difficulty: 4,
    difficultyLabel: "Zor",
    description: "Teknik çizim loader’ı kısa bir hero kartına dönüşür.",
    instruction: "Tıkla",
  },
];
